import HomeLayout from "@/layout/HomeLayout";
import "./globals.css";
import { FONTS } from "@/utils/font";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={ FONTS }>
      <HomeLayout  >
        {children}
      </HomeLayout>
    </html>
  );
}
